 let &t_SI = "\<Esc>]50;CursorShape=1\x7"
 let &t_SR = "\<Esc>]50;CursorShape=2\x7"
 let &t_EI = "\<Esc>]50;CursorShape=0\x7"
 set ttimeout
 set ttimeoutlen=1
 set listchars=tab:>-,trail:~,extends:>,precedes:<,space:.
 set ttyfast

 syntax on
 filetype plugin on

 lua require('vim')
 luafile ~/.config/nvim/lua/keymaps.lua
 luafile ~/.config/nvim/lua/settings.lua
 lua << EOF
 -- Vô hiệu hóa các plugin mặc định không cần thiết trong Neovim
local disabled_built_ins = {
	"getscript",
	"getscriptPlugin",
	"logipat",
	"spellfile_plugin",
	"compiler",
	"ftplugin",
	"netrw",
	"netrwPlugin",
	"netrwSettings",
	"netrwFileHandlers",
}
for _, plugin in pairs(disabled_built_ins) do
	vim.g["loaded_" .. plugin] = 1
end
EOF

packadd comment

 if executable('ibus') == 0
   finish
 endif

 function! CurrentIbusEngine()
   let output = systemlist('ibus engine')
   return output[0]
 endfunction

 function! IBusOff()
   let g:ibus_prev_engine = CurrentIbusEngine()
   call system('ibus engine xkb:us::eng')
 endfunction

 function! IBusOn()
   let current_engine = CurrentIbusEngine()
   if current_engine !~ 'xkb:us::eng'
     let g:ibus_prev_engine = current_engine
   endif
   call system('ibus engine ' . trim(g:ibus_prev_engine))
 endfunction

 augroup IBusHandler
   autocmd!
   autocmd CmdlineEnter [/?] call IBusOn()
   autocmd CmdlineLeave [/?] call IBusOff()
   autocmd InsertEnter * call IBusOn()
   autocmd InsertLeave * call IBusOff()
   autocmd ExitPre * call IBusOn()
 augroup END

 call IBusOff()
