let &t_SI = "\<Esc>]50;CursorShape=1\x7"
let &t_SR = "\<Esc>]50;CursorShape=2\x7"
let &t_EI = "\<Esc>]50;CursorShape=0\x7"
set ttimeout
set ttimeoutlen=1
set listchars=tab:>-,trail:~,extends:>,precedes:<,space:.
set ttyfast

syntax on
filetype plugin on
packadd comment

lua require('vim')
luafile ~/.config/nvim/lua/keymaps.lua
luafile ~/.config/nvim/lua/settings.lua
luafile ~/.config/nvim/lua/ibus.lua

if executable('ibus')
	augroup IBusHandler
	  autocmd!
	  autocmd CmdlineEnter [/?] lua IbusOn()
	  autocmd CmdlineLeave [/?] lua IbusOff()
	  autocmd InsertEnter * lua IbusOn()
	  autocmd InsertLeave * lua IbusOff()
	  autocmd ExitPre * lua IbusOn()
	augroup END
endif
