if !has('lua')
	echoerr "This Vim is not compiled with Lua support."
endif
if !has('python3')
	let &pythonthreedll = split(system('ldconfig -p | grep libpython3'))[0]
	if !has('python3')
		echoerr "This Vim is not compiled with Python3 support."
	endif
endif

let s:file = expand('<sfile>')

function! s:setup()
	let s:nvim_config = trim(systemlist('nvim -l ' . fnamemodify(s:file, ':h') . '/.lua')[0])
	execute 'source ' . s:nvim_config . '/vimrc'
endfunction

autocmd VimEnter * call s:setup()

packadd! lazy/vim-dirvish
let g:dirvish_mode = ':sort ,^.*[\\/],'
if has('lua')
	packadd! lazy/dirvish-git.nvim
	packadd! lazy/autosave.nvim
	packadd! lazy/copilot.vim
endif
