if !has('lua')
	echoerr "This Vim is not compiled with Lua support."
endif
if !has('python3')
	let &pythonthreedll = split(system('ldconfig -p | grep libpython3'))[0]
	if !has('python3')
		echoerr "This Vim is not compiled with Python3 support."
	endif
endif

let s:vimrc = system('nvim --headless --clean -c "=vim.fn.stdpath([[config]])" -c qa!')
execute 'source ' . s:vimrc . '/vimrc'

packadd! lazy/vim-dirvish
let g:dirvish_mode = ':sort ,^.*[\\/],'
if has('lua')
	packadd! lazy/dirvish-git.nvim
	packadd! lazy/autosave.nvim
	packadd! lazy/copilot.vim
endif
