let &t_SI = "\<Esc>]50;CursorShape=1\x7"
let &t_SR = "\<Esc>]50;CursorShape=2\x7"
let &t_EI = "\<Esc>]50;CursorShape=0\x7"
set ttimeout
set ttimeoutlen=1
set listchars=tab:>-,trail:~,extends:>,precedes:<,space:.
set ttyfast

syntax on
filetype plugin on
packadd comment

lua require('vim')
luafile ~/.config/nvim/lua/keymaps.lua
luafile ~/.config/nvim/lua/settings.lua
luafile ~/.config/nvim/lua/ibus.lua
luafile ~/.config/nvim/lua/plugins-managers.lua

if executable('ibus')
	augroup IBusHandler
		autocmd!
		autocmd CmdLineEnter [/?] :s/ :%s/ call IbusOn()
		autocmd CmdLineLeave [/?] :s/ :%s/ call IbusOff()
		autocmd InsertEnter * lua IbusOn()
		autocmd InsertLeave * lua IbusOff()
		autocmd ExitPre * lua IbusOn()
	augroup END
endif

lua require('copilot')
packadd lazy/copilot.vim
packadd lazy/vim-dirvish
packadd lazy/vim-dirvish-git
packadd lazy/vim-fugitive
packadd lazy/vim-dadbod
packadd lazy/vim-dadbod-completion
packadd lazy/vim-dadbod-ui
