"silent language vi_VN.utf-8

set mouse=nv
set number
set noexpandtab
set autoindent
set smartindent
set nocursorline
set shiftwidth=4
set tabstop=4
set clipboard=unnamedplus
set autowriteall
set nomodeline
set backspace=indent,eol,start
set noswapfile
set backupcopy=yes
let g:mapleader=" "

if has('nvim')
	set foldexpr=v:lua.vim.treesitter.foldexpr()
	set omnifunc=v:lua.vim.treesitter.query.omnifunc
	aunmenu PopUp
  	autocmd! nvim_popupmenu
endif

nnoremap t :call Terminal()<CR>
xnoremap t :call Terminal()<CR>
tnoremap <Esc> <C-\><C-n>

nnoremap <BS> "_d
xnoremap <BS> "_d
nnoremap <BS><BS> "_dd
xnoremap <BS><BS> "_dd
nnoremap <Del> "_D
xnoremap <Del> "_D
nnoremap Y y$
xnoremap Y y$

let did_install_default_menus = 1
let did_install_syntax_menu = 1

function! IBusOff()
	let g:ibus_prev_engine = trim(system('ibus engine'))
	execute 'silent !ibus engine xkb:us::eng'
endfunction

function! IBusOn()
	let l:current_engine = trim(system('ibus engine'))
	if l:current_engine !~? 'xkb:us::eng'
		let g:ibus_prev_engine = l:current_engine
	endif
	execute 'silent !' . 'ibus engine ' . g:ibus_prev_engine
endfunction

if executable('ibus')
	augroup IBusHandler
		autocmd CmdLineEnter [/?],[:s/?],[:%s/?] call IBusOn()
		autocmd CmdLineLeave [/?],[:s/?],[:%s/?] call IBusOff()
		autocmd InsertEnter * call IBusOn()
		autocmd InsertLeave * call IBusOff()
		autocmd FocusGained * call IBusOn()
		autocmd FocusLost * call IBusOff()
		autocmd ExitPre * call IBusOn()
	augroup END
	call IBusOff()
else
	echoerr "ibus is not installed. Switch to keymap vietnamese-telex_utf-8."
	set keymap=vietnamese-telex_utf-8
endif

function! Terminal()
	if &buftype == 'terminal'
		startinsert
		return
	endif
	let term_win = -1
	for win in range(1, winnr('$'))
		execute win . 'wincmd w'
		if &buftype == 'terminal'
			let term_win = win
			break
		endif
	endfor
	if term_win == -1
		belowright split | terminal
		setlocal nonumber
		set winheight=12
	else
		execute term_win . 'wincmd w'
	endif
	startinsert
endfunction

if !has('nvim')
	let &t_SI = "\<Esc>]50;CursorShape=1\x7"
	let &t_SR = "\<Esc>]50;CursorShape=2\x7"
	let &t_EI = "\<Esc>]50;CursorShape=0\x7"
	set ttimeout
	set ttimeoutlen=1
	set listchars=tab:>-,trail:~,extends:>,precedes:<,space:.
	set ttyfast
	let &t_TI = "\<Esc>[>4;2m"
    let &t_TE = "\<Esc>[>4;m"

	set nocompatible
	syntax on
	filetype plugin on
	packadd! comment
	packadd! matchit
	runtime! ftplugin/man.vim
	if !has('clipboard')
		echoerr "This Vim is not compiled with clipboard support."
	endif

	packadd! lazy/vim-dirvish
	if has('lua')
		packadd! lazy/autosave.nvim
		packadd! lazy/dirvish-git.nvim
	endif
endif
