GOOSE_PROVIDER: github_copilot
GOOSE_MODE: smart_approve
GOOSE_MODEL: gpt-4.1
extensions:
  computercontroller:
    bundled: true
    display_name: Computer Controller
    enabled: true
    name: computercontroller
    timeout: 300
    type: builtin
  developer:
    bundled: true
    display_name: Developer Tools
    enabled: true
    name: developer
    timeout: 300
    type: builtin
  nvim-mcp:
    args: []
    bundled: null
    cmd: nvim-mcp
    description: An extension to control a parent Nvim instance.
    enabled: true
    env_keys: []
    envs: {}
    name: nvim-mcp
    timeout: 300
    type: stdio
  tutorial:
    bundled: true
    display_name: Tutorial
    enabled: true
    name: tutorial
    timeout: 300
    type: builtin
